version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "electron"
      - dependency-name: "spectron"
      - dependency-name: "typescript"
      - dependency-name: "sass-loader"
        versions: ["11.x"]
      - dependency-name: "@types/node"
