version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  ignore:
  - dependency-name: electron
  - dependency-name: spectron

- package-ecosystem: npm
  directory: "/nuxt/"
  open-pull-requests-limit: 0
  schedule:
    interval: "weekly"
